language: csharp
dist: xenial
env:
  global:
    - Configuration=Release
    - ASPNETCORE_ENVIRONMENT=Staging
dotnet: 2.1.402
mono: none
branches:
  only:
  - master
  - /^release\/.*$/
  - develop
before_install:
  - chmod +x build.sh
script:
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - ./build.sh
 
