language: csharp
dist: xenial
env:
  global:
    - Configuration=Release
    - ASPNETCORE_ENVIRONMENT=Staging
dotnet: 2.1.402
mono: none
branches:
  only:
  - master
  - /^release\/.*$/
  - develop
script:
 - ./build.sh
