language: csharp
dist: xenial
env:
  global:
    - Configuration=Release
    - ASPNETCORE_ENVIRONMENT=Staging
dotnet: 2.1.500
mono: none
branches:
  only:
  - master
  - /^release\/.*$/
  - develop
before_install:
  - chmod +x build.sh
script:
  - dotnet --info
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - dotnet tool install -g Cake.Tool
  - dotnet tool list  -g
  - ./build.sh --verbosity=diagnostic
