version: '{build}'
image:
- Visual Studio 2017
- Ubuntu
configuration: Release
environment:
  ASPNETCORE_ENVIRONMENT: Staging
nuget:
  project_feed: true
  disable_publish_on_pr: true
artifacts:
- path: build\artifacts\*.nupkg
deploy: off
branches:
  only:
    - develop
    - /release.*/ 
    - master
skip_commits:
  files:
  - LICENSE
  - README.md
  - .travis.yml
  - WebInfrastructure.sln.DotSettings
for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
    build_script:
      - ps: >-
          .\build.ps1 -target CalculateCoverage --settings_skipverification=true
        
  -
    matrix:
      only:
        - image: Ubuntu
    build_script:
      - sh: >-
          ./build.sh
