version: '{build}'
image:
- Visual Studio 2017
- Ubuntu
configuration: Release

cache:
  - tools -> build.cake
  - packages -> **\packages.config, nuget.config

environment:
  ASPNETCORE_ENVIRONMENT: Staging

nuget:
  project_feed: true
  disable_publish_on_pr: true

artifacts:
- path: build\artifacts\*.nupkg

deploy: off
branches:
  only:
    - develop
    - /release.*/ 
    - master
skip_commits:
  files:
  - LICENSE
  - README.md
  - .travis.yml
  - WebInfrastructure.sln.DotSettings
for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
    before_build:
      - choco install codecov    
    build_script:
      - ps: >-
          .\build.ps1 -BuildEnvironment "cloud"
        
  -
    matrix:
      only:
        - image: Ubuntu
    build_script:
      - chmod +x build.sh
      - ./build.sh
