trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:

- template: azure-pipelines.template.yml
  parameters:
    name: ubuntu_node_8
    vmImage: 'ubuntu-16.04'
    node_version: 8.x

- template: azure-pipelines.template.yml
  parameters:
    name: ubuntu_node_9
    vmImage: 'ubuntu-16.04'
    node_version: 9.x


- job: Linux 
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: chmod +x ./build.sh
  - script: |
      docker login -u navigatordatastore -p NavigatorDataStore2016
      docker build -f docker/azuredevopskats-web-local.dockerfile/Dockerfile -t stuartshay/azuredevopskats:devops  .
      docker push stuartshay/azuredevopskats:devops 
    displayName: 'Cake Build'
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - bash: chmod +x ./build.sh
    displayName: 'Cake Build'
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: .\build.ps1
    displayName: 'Cake Build'
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: artifacts

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

    CleanTargetFolder: true


- task: NuGetCommand@2
  displayName: 'Push To Myget'
  inputs:
    command: push

    nuGetFeedType: external

    publishFeedCredentials: MyGet


