jobs:

- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.node_version }}
    displayName: 'Install Node.js'

  - script: >
      dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
