version: '2.2'

services:

  redis:
    container_name: 'redis'
    hostname: redis
    image: stuartshay/navigator-identity-redis:development
    ports:
      - "6379:6379"
    volumes:
      - redis-data-volume:/var/lib/redis
    restart: always
    networks:
      - navigator-identity-network

  mongo:
    container_name: 'mongo'
    hostname: mongo
    image: "stuartshay/navigator-instance:latest"
    volumes:
      - mongo-data-volume:/data/db
      - mongo-config-volume:/data/config
      - mongo-backup-volume:/backup
    ports:
      - "27017:27017"
      - "28017:28017"
    restart: always
    networks:
      - navigator-identity-network

  mail:
    container_name: 'mail'
    hostname: mail
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - navigator-identity-network

volumes:
  redis-data-volume:
  nginx-log-volume:
  sql-data-volume:
  www-root-volume:
  mongo-data-volume:
  mongo-config-volume:
  mongo-backup-volume:

networks:
  web-network:
    driver: bridge
